var sampleAds = [
  {
    id: "A101",
    fecha_publicacion: "2025-08-20 10:30",
    fecha_entrega: "2025-08-23 12:00",
    comuna: "Puente Alto",
    sector: "Villa Alegre",
    cantidad: 1,
    tipo: "perro",
    edad: "8 años",
    nombre: "Perla",
    contacto: "+569.91234567 (whatsapp)",
    total_fotos: 1,
    fotos: ["../Imagenes/Perla.jpg"],
    descripcion: "Perla es muy cariñosa y enérgica. Ideal para patio."
  },
  {
    id: "A102",
    fecha_publicacion: "2025-08-19 09:00",
    fecha_entrega: "2025-08-25 15:00",
    comuna: "Ñuñoa",
    sector: "Barrio Italia",
    cantidad: 1,
    tipo: "gato",
    edad: "6 años",
    nombre: "Nina",
    contacto: "Nina@gmail.com (email)",
    total_fotos: 2,
    fotos: ["../Imagenes/Nina_1.jpg", "../Imagenes/Nina_2.jpg"],
    descripcion: "Nina es muy tranquila, le encanta dormir largos ratos y acurrucarse. Perfecta para departamento."
  },
  {
    id: "A103",
    fecha_publicacion: "2025-08-18 11:20",
    fecha_entrega: "2025-08-28 10:00",
    comuna: "La Florida",
    sector: "Paradero 25",
    cantidad: 1,
    tipo: "gato",
    edad: "2 meses",
    nombre: "Ramona",
    contacto: "+569.49027186 (whatsapp)",
    total_fotos: 1,
    fotos: ["../Imagenes/Ramona.jpg"],
    descripcion: "Ramona es juguetona y curiosa, muy sociable con personas y otros animales. Necesita paciencia y cuidados propios de su edad."
  },
  {
    id: "A104",
    fecha_publicacion: "2025-08-15 14:00",
    fecha_entrega: "2025-09-02 09:00",
    comuna: "Santiago Centro",
    sector: "San Diego",
    cantidad: 1,
    tipo: "gato",
    edad: "10 años",
    nombre: "Cholo",
    contacto: "+569.99887766 (telegram)",
    total_fotos: 1,
    fotos: ["../Imagenes/Cholo.jpg"],
    descripcion: "Cholo es muy tranquilo y obediente; ideal para personas mayores. Gran compañero y de buen carácter."
  },
  {
    id: "A105",
    fecha_publicacion: "2025-09-02 08:45",
    fecha_entrega: "2025-09-08 16:30",
    comuna: "Vitacura",
    sector: "Parque Norte",
    cantidad: 1,
    tipo: "perro",
    edad: "4 meses",
    nombre: "Guante",
    contacto: "+569.91882047 (telegram)",
    total_fotos: 1,
    fotos: ["../Imagenes/Guante.jpg"],
    descripcion: "Guante es enérgico y juguetón, perfecto para quienes dispongan de tiempo para jugar."
  }
];